instance_region             = "us-southeast"
instance_type               = "g6-nanode-1"
domain_name                 = "siwko.org"
domain_name_alt             = "siwko.net"
domain_soa_email            = "asiwko@siwko.org"
letsencrypt_email           = "asiwko@siwko.org"
qha_admin_hostname          = "qha-admin"
wireguard_client_public_key = "VbWyEnaj4zpZFadRGyg3Ei93ohDxvdU6qgOBzzdZfDA="
