instance_region    = "us-southeast"
instance_type      = "g6-nanode-1"
domain_name        = "siwko.org"
domain_soa_email   = "asiwko@siwko.org"
letsencrypt_email  = "asiwko@siwko.org"
qha_admin_hostname = "qha-admin"
